---
- name: install windows applications
  hosts: Windows
  tasks:
    - name: Install Firefox and 7zip
      win_chocolatey:
        name: 
        - firefox
        - 7zip
        - notepadplusplus
        state: present
